# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
use_frameworks!

target 'AutolayoutTests' do
	pod 'commons', :path => '~/work/commons'
end

target 'AutolayoutTestsTests' do

end

